ALTER TABLE UserRoles
ADD CONSTRAINT PK_UserRoles PRIMARY KEY (UserId, RoleId);

ALTER TABLE UserRoles
ADD CONSTRAINT FK_UserRoles_User
FOREIGN KEY (UserId) REFERENCES Riders(RiderId) ON DELETE CASCADE;

ALTER TABLE UserRoles
ADD CONSTRAINT FK_UserRoles_Role
FOREIGN KEY (RoleId) REFERENCES Roles(RoleId) ON DELETE CASCADE;

ALTER TABLE Repairs
ADD CONSTRAINT FK_Repairs_Motorcycle
FOREIGN KEY (MotorcycleId) REFERENCES Motorcycles(MotorcycleId) ON DELETE CASCADE;