CREATE TABLE Riders (
RiderId INT PRIMARY KEY IDENTITY
FirstName NVARCHAR (100),
LastName NVARCHAR (100),
JoinDate DATA
);

CREATE TABLE Roles(
RoleId INT PRIMARY KEY IDENTITY (1,1),
RoleName NVARCHAR (50) NOT NULL UNIQUE
);

CREATE TABLE UserRoles(
UserId INT NO NULL,
RoleId INT NOT NULL,
PRIMARY KEY (UserId, RoleId)
PRIMARY KEY(UserId) REFERENCES Users (UserId) ON DELETE CASCADE,
FOREIGN KEY(RoleId) REFERENCES Roles (RoleId) ON DELETE CASCADE 
);